# Generated by Django 5.1.1 on 2024-09-29 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0002_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='modile',
            new_name='mobile',
        ),
    ]
